[project]
name = "03-api-sec"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi-mcp>=0.3.4",
    "httpx>=0.28.1",
    "logging>=0.4.9.6",
    "pytest>=8.3.5",
    "pytest-asyncio>=1.0.0",
]
